spring:
  application:
    name: IMDB-MDS
server:
  port: 7000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled: true

imdb:
  movies:
    url: https://datasets.imdbws.com/title.basics/search
    filename: imdb_top_1000.csv

users:
  storage:
    path: ./src/main/resources/data/users.json
